name: Build image Docker

on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Descargar el proyecto
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Construir imagen & push docker image
        with:
          image: sebasspp/transaccion
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.USUARIODEPOSITOS }}
          password: ${{ secrets.CONTRASENADEPOSITOS }}